const { verifyToken } = require('../middlewares/authMiddleware');
const route = require('express').Router();
const signInRoute = require('./signInRoute');
const signUpRoute = require('../routes/signUpRoute');
const userRoute = require('../routes/userRoute');
const projectRoute = require('../routes/projectRoute');
const userProjectRoute = require('../routes/userProjectRoute');
const stageRoute = require('../routes/stageRoute');
const taskRoute = require('../routes/taskRoute');
const taskUserRoute = require('../routes/taskUserRoute');
const assessmentRoute = require('../routes/assessmentRoute');
const commentRoute = require('../routes/commentRoute');
const mentionRoute = require('../routes/mentionRoute');
route.use('/sign-in', signInRoute);
route.use('/sign-up', signUpRoute);
route.use(verifyToken);
route.use('/user', userRoute);
route.use('/project', projectRoute);
route.use('/user-project', userProjectRoute);
route.use('/stage', stageRoute);
route.use('/task', taskRoute);
route.use('/task-user', taskUserRoute);
route.use('/assessment', assessmentRoute);
route.use('/comment', commentRoute);
route.use('/mention', mentionRoute);
module.exports = route;
